baseURL = '/'
languageCode = 'en-us'
title = 'Bus Pirate Documentation'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    [[module.imports]]
        path = "cj.rs/gohugo-asciinema"
        disable = false

[params]

  google_fonts = [
    ["Manrope", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Manrope"     # Default is System font
  secondary_font  = "Manrope"     # Default is System font
  mono_font       = "Fira Code" # Default is System font

    [params.docs] # Parameters for the /docs 'template'
        title           = "Bus Pirate Docs"           # default html title for documentation pages/sections
        themeColor      = "dark-red"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
        darkMode        = true                                # enable dark mode option? default false
        logo = "images/logos/danger.png"
        keywords = "Hardware hacking, debugging, learn electronics"

    [params.footer] 
        copyright       = "Copyright © 2025 Where Labs, LLC. Built with Open Source."
    
    [params.asciinema.defaults]
        autoPlay = true
        loop = true
        fit = "width"
        idleTimeLimit = 2
        controls = "auto"
        cols = 80
        rows = 24

[menu]
[[menu.primary]]
    name  = "Bus Pirate"
    url = "https://buspirate.com/"
    weight = 10
[[menu.primary]]
    name  = "Downloads"
    url = "/docs/downloads/"
    weight = 20
[[menu.primary]]
    name  = "Docs"
    url = "https://docs.buspirate.com/"
    weight = 30
[[menu.primary]]
    name  = "Forum"
    url = "https://forum.buspirate.com/"
    weight = 40
[[menu.primary]]
    name  = "Get"
    url = "https://buspirate.com/get"
    weight = 15
[[menu.primary]]
    name  = "Contact"
    url = "https://buspirate.com/contact"
    weight = 60

 
[[menu.footer]]
    name  = "Distributors"
    weight = 10

[[menu.footer]]
    name = "Get Bus Pirate"
    url = "https://buspirate.com/get"
    parent = "Distributors"

[[menu.footer]]
    name = "Quick Links"
    weight = 20

[[menu.footer]]
    name = "Documentation"
    url = "https://docs.buspirate.com/"
    parent = "Quick Links"

[[menu.footer]]
    name = "Downloads"
    url = "http://localhost:1313/docs/downloads/"
    parent = "Quick Links"    

[[menu.footer]]
    name = "Community"
    weight = 30

[[menu.footer]]
    name = "Forum"
    url = "https://forum.buspirate.com/"
    parent = "Community"

[[menu.footer]]
    name = "Mastodon"
    url = "https://mastodon.social/@buspirate"
    parent = "Community"

[[menu.footer]]
    name = "BlueSky"
    url = "https://bsky.app/profile/buspirate.bsky.social"
    parent = "Community"

[[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/dangerousprototypes/"
    parent = "Community"

[[menu.footer]]
    name = "X (Twitter)"
    url = "https://twitter.com/dangerousproto"
    parent = "Community"    

[[menu.footer]]
    name = "More"
    weight = 40

[[menu.footer]]
    name = "Blog"
    url = "https://buspirate.com/"
    parent = "More"  

[[menu.footer]]
    name = "Contact"
    url = "https://buspirate.com/contact"
    parent = "More"

[[menu.footer]]
    name = "GitHub"
    url = "https://github.com/DangerousPrototypes"
    parent = "More"


[markup.goldmark.renderer]
  unsafe = true
